import { z } from "zod";

// Input source - where a session/job originated
export const InputSource = z.enum(["slack", "meet"]);
export type InputSource = z.infer<typeof InputSource>;

// Reasoning effort levels for OpenAI models
export const ReasoningEffort = z.enum(["none", "low", "medium", "high", "xhigh", "auto"]);
export type ReasoningEffort = z.infer<typeof ReasoningEffort>;

// Verbosity levels for GPT-5.2 output
export const Verbosity = z.enum(["low", "medium", "high"]);
export type Verbosity = z.infer<typeof Verbosity>;

// Session configuration - controls how Claire behaves
export const SessionConfig = z.object({
  repo: z.string().optional(),
  branch: z.string().optional(),
  model: z.string().default("gpt-5.2"),
  scope: z.enum(["thread", "channel"]).default("thread"),
  channelLimit: z.number().optional(),
  mode: z.enum(["code", "chat"]).default("code"),
  reasoningEffort: ReasoningEffort.default("medium"),
  verbosity: Verbosity.optional(), // Defaults to model's default (medium)
  enableWebSearch: z.boolean().default(true),
  enableCodeInterpreter: z.boolean().default(false), // Use local bash instead
});
export type SessionConfig = z.infer<typeof SessionConfig>;

// Session - maps 1:1 with a Slack thread (or Meet binding)
export const Session = z.object({
  id: z.string().uuid(),
  channelId: z.string(),
  threadTs: z.string(),
  config: SessionConfig,
  status: z.enum(["idle", "running", "aborted", "completed"]),
  source: InputSource.default("slack"),
  createdAt: z.coerce.date(),
  updatedAt: z.coerce.date(),
});
export type Session = z.infer<typeof Session>;

// Job - a single task within a session
export const Job = z.object({
  id: z.string().uuid(),
  sessionId: z.string().uuid(),
  promptMessageTs: z.string(),
  promptText: z.string(),
  userId: z.string(), // Slack user ID or "meet:<speaker>" for Meet jobs
  status: z.enum(["queued", "running", "succeeded", "failed", "aborted"]),
  source: InputSource.default("slack"),
  sourceMeta: z.record(z.unknown()).optional(), // Meet-specific metadata
  startedAt: z.coerce.date().optional(),
  endedAt: z.coerce.date().optional(),
  resultSummary: z.string().optional(),
});
export type Job = z.infer<typeof Job>;

// Control updates - parsed from user messages
export const ControlUpdate = z.object({
  type: z.enum([
    "repo", "branch", "model", "scope", "mode",
    "stop", "abort", "save", "load",
    "reasoning", "verbosity", "websearch", "codeinterpreter",
    "help", "profile"
  ]),
  value: z.string().optional(),
});
export type ControlUpdate = z.infer<typeof ControlUpdate>;

// Attachment metadata
export const AttachmentMeta = z.object({
  id: z.string(),
  name: z.string(),
  mimetype: z.string(),
  url: z.string(),
  extractedText: z.string().optional(),
  localPath: z.string().optional(),
});
export type AttachmentMeta = z.infer<typeof AttachmentMeta>;

// Message snapshot - captures a Slack message for context
export const MessageSnapshot = z.object({
  id: z.string(),
  sessionId: z.string().uuid(),
  ts: z.string(),
  userId: z.string(),
  text: z.string(),
  attachments: z.array(AttachmentMeta),
});
export type MessageSnapshot = z.infer<typeof MessageSnapshot>;

// Artifact - outputs generated by Claire
export const Artifact = z.object({
  id: z.string().uuid(),
  sessionId: z.string().uuid(),
  jobId: z.string().uuid(),
  type: z.enum(["image", "pdf", "log", "archive", "code", "other"]),
  filename: z.string(),
  storageKey: z.string(),
  slackFileId: z.string().optional(),
  size: z.number().optional(),
  createdAt: z.coerce.date(),
});
export type Artifact = z.infer<typeof Artifact>;

// Git action log - tracks git operations
export const GitAction = z.object({
  id: z.string().uuid(),
  sessionId: z.string().uuid(),
  jobId: z.string().uuid(),
  repo: z.string(),
  branch: z.string(),
  operation: z.enum(["clone", "checkout", "commit", "push", "pr"]),
  commits: z.array(z.string()),
  prUrl: z.string().optional(),
  createdAt: z.coerce.date(),
});
export type GitAction = z.infer<typeof GitAction>;

// Channel config - stores last-used repo per channel
export const ChannelConfig = z.object({
  channelId: z.string(),
  lastRepo: z.string().optional(),
  lastBranch: z.string().optional(),
  updatedAt: z.coerce.date(),
});
export type ChannelConfig = z.infer<typeof ChannelConfig>;

// User profile - persistent memory of user preferences and interaction style
export const UserProfile = z.object({
  userId: z.string(),
  displayName: z.string(),
  profile: z.string(), // Freeform profile text maintained by LLM
  interactionCount: z.number().default(0),
  createdAt: z.coerce.date(),
  updatedAt: z.coerce.date(),
});
export type UserProfile = z.infer<typeof UserProfile>;

// Tool call representation
export const ToolCall = z.object({
  id: z.string(),
  name: z.string(),
  input: z.record(z.unknown()),
});
export type ToolCall = z.infer<typeof ToolCall>;

// Tool result
export const ToolResult = z.object({
  output: z.string(),
  error: z.string().optional(),
  metadata: z.record(z.unknown()).optional(),
});
export type ToolResult = z.infer<typeof ToolResult>;

// LLM message format
export const LLMMessage = z.discriminatedUnion("role", [
  z.object({
    role: z.literal("system"),
    content: z.string(),
  }),
  z.object({
    role: z.literal("user"),
    content: z.string(),
  }),
  z.object({
    role: z.literal("assistant"),
    content: z.string(),
    toolCalls: z.array(ToolCall).optional(),
  }),
  z.object({
    role: z.literal("tool"),
    toolCallId: z.string(),
    content: z.string(),
  }),
]);
export type LLMMessage = z.infer<typeof LLMMessage>;

// Meet binding - maps Google Meet URL to Slack thread
export const MeetBinding = z.object({
  meetUrl: z.string(),
  channelId: z.string(),
  threadTs: z.string(),
  createdBy: z.string(), // Slack user ID who created the binding
  createdAt: z.coerce.date(),
  expiresAt: z.coerce.date().optional(),
});
export type MeetBinding = z.infer<typeof MeetBinding>;
